### ISSUE TITLE
Continue with Vagrant after a plugin is install

### ISSUE THREAD

**Issue by humansky** [DevNIX/Vagrant-dependency-manager#2]
This is a fantastic project and has already been a valuable addition to our development workflow. The only thing I noticed, vagrant doesn't continue after it installs a plugin. Not a big deal, if we run vagrant up again, it works fine. Is it possible to continue the `vagrant up` process after a plugin is install?

Here's an example:

![screen shot 2016-08-24 at 3 53 00 pm](https://cloud.githubusercontent.com/assets/184953/17945686/e955fd0e-6a12-11e6-88b9-cd9f8693b1ac.png)

**Comment by devnix** [comment]
Thank you, I feel glad that it helped you!

It's been a few months since I used this project in favor of docker-compose. The dependency manager should continue after installing, so it could be a bug in a Vagrant update.

Could you please give me your running Vagrant version so I can try to reproduce the bug?

**Comment by devnix** [comment]
Just saw your edit. Could you please paste here too your Vagrantfile and check that you are using the v0.2 version of Vagrant dependency manager?

**Comment by humansky** [comment]
Thank you for the quick reply. Here's my Vagrantfile:

https://gist.github.com/humansky/47e337ba2773a59e17bdcb4e507c46f6

And I'm using the latest HEAD version of dependency_manager:

https://raw.githubusercontent.com/DevNIX/Vagrant-dependency-manager/master/dependency_manager.rb

I'll verify again by uninstalling the plugins and trying again.

**Comment by devnix** [comment]
And your Vagrant version? :)

**Comment by humansky** [comment]
That would help....using the latest version 1.8.5. I actually require the latest version in my Vagrant file, because I was getting another even stranger error with 1.8.4, which seems to have been fixed with the latest version.

**Comment by humansky** [comment]
Not sure if this is related, but I tried adding another Vagrant plugin to test and now I'm getting this error:

``` bash
~/workspace/princeton/pwds/pwds-vm(master ✗) vagrant up
Checking dependencies...
 - Missing 'landrush'!
Installing the 'landrush' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing eventmachine (1.0.9.1), and Bundler cannot continue.
Make sure that `gem install eventmachine -v '1.0.9.1'` succeeds before bundling.

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /opt/vagrant/embedded/bin/ruby -r ./siteconf20160824-15736-17yyjvi.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/vagrant/embedded/bin/$(RUBY_BASE_NAME)
        --with-ssl-dir
        --without-ssl-dir
        --with-ssl-include
        --without-ssl-include=${ssl-dir}/include
        --with-ssl-lib
        --without-ssl-lib=${ssl-dir}/lib
        --with-openssl-config
        --without-openssl-config
        --with-pkg-config
        --without-pkg-config
/opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:535:in `block in try_link0'
        from /opt/vagrant/embedded/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'
        from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:532:in `try_link0'
        from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:556:in `try_link'
        from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:637:in `try_ldflags'
        from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:1780:in `pkg_config'
        from extconf.rb:65:in `pkg_config_wrapper'
        from extconf.rb:92:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/humansky/.vagrant.d/gems/gems/eventmachine-1.0.9.1 for inspection.
Results logged to /Users/humansky/.vagrant.d/gems/extensions/universal-darwin-12/2.2.0/eventmachine-1.0.9.1/gem_make.out


 - Could not install plugin 'landrush'. Stopped.
~/workspace/princeton/pwds/pwds-vm(master ✗) 
```

**Comment by devnix** [comment]
Could you please try to install `landrush`plugin manually?

**Comment by humansky** [comment]
Well that's embarrassing, it doesn't work outside the context of your script 😄

**Comment by devnix** [comment]
But I can confirm your first issue!

```
Vagrant:
* Unknown configuration section 'bindfs'.
```

Probably Vagrant is not loading the installed plugin until you launch it again. Let me hack something :D

**Comment by devnix** [comment]
Could you please use the `dependency_manager.rb` from the pull request #3, and follow the next steps?
1. Open a terminal and execute `vagrant plugin uninstall vagrant-bindfs`
2. I have just added a new option.
   
   You can bypass the dependency manager by running `vagrant --skip-dependency-manager up` instead of `vagrant up`. You can check it, you should get a `* Unknown configuration section 'bindfs'.` message.
3. Run `vagrant up`
4. Check if Vagrant Dependency Manager installs the dependency for you and bootstraps normally
   If you can confirm it I will close the issue, add a new number to the semver and release a new version.

This is the very first time I gave support of a piece of software released by myself, and the first notice I had about my code running somewhere.

If you have any cool idea or have any feature for this project, just open a new issue or contact me on Gitter. You absolutely made my day, thank you! :heart:

**Comment by humansky** [comment]
The new script in PR #3 worked like a charm. This is a fantastic script and the essence of open source. Thank you!!!

**Comment by devnix** [comment]
Bugfix released: https://github.com/DevNIX/Vagrant-dependency-manager/releases/tag/v0.3

Thank you so much! I'm considering to investigate the way to auto-update the dependency manager :)
