### ISSUE TITLE
Error with using "--provision" option

### ISSUE THREAD

**Issue by andkirby** [DevNIX/Vagrant-dependency-manager#4]
When I used with `--provision` option I got the error:

```
$ vagrant reload --provision
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/bin/vagrant: unrecognized option `--provision'
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: D:/vms/docker/Vagrantfile
Line number: 0
Message: GetoptLong::InvalidOption: unrecognized option `--provision'
```

It looks like `Vagrant-dependency-manager` has its own options list which doesn't match with Vagrant one.
Without using `Vagrant-dependency-manager` Vagrant works fine.

**Comment by devnix** [comment]
Yup, going to remove the `getoptlong` piece and threat the argument manually. Thank you for your feedback!

**Comment by devnix** [comment]
Fixed and published, check the latest release https://github.com/DevNIX/Vagrant-dependency-manager/releases/tag/0.3.1 :)

**Comment by andkirby** [comment]
Thanks for quick fix! 👍 :)

**Comment by devnix** [comment]
You're welcome, thanks for the feedback!
